# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_assignment_login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'BEMCheckBox'
  # Pods for iOS_assignment_login

  target 'iOS_assignment_loginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_assignment_loginUITests' do
    # Pods for testing
  end

end
